[package]
name = "ip2asn"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
ip_network = "0.4.1"
serde = { version = "1.0", features = ["derive"], optional = true }
ip_network_table = "0.2.0"
flate2 = "1.0"
reqwest = { version = "0.12.5", features = ["blocking"], optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
wiremock = "0.6.0"

[features]
serde = ["dep:serde"]
fetch = ["dep:reqwest"]
